-- July 2026 CCTV Facility Inspection Schedule
-- SQL INSERT statements for bulk loading

INSERT INTO inspection_schedule (inspection_date, inspector_id, template_id, site_id, location, status, created_at) VALUES
('2026-07-02', (SELECT id FROM users WHERE fullname LIKE '%Hatem Ben Brahim%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Gerbeurs%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-03', (SELECT id FROM users WHERE fullname LIKE '%Rim Ben Boujemaa%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Blocs Autonomes%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-05', (SELECT id FROM users WHERE fullname LIKE '%Ahlem Lellahom%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Zones de Stockage%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-06', (SELECT id FROM users WHERE fullname LIKE '%Dalel Ben Dhieb%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Portes Coupe-Feu%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-07', (SELECT id FROM users WHERE fullname LIKE '%Ahlem Lellahom%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Quais de Chargement%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-09', (SELECT id FROM users WHERE fullname LIKE '%Rim Ben Boujemaa%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Kit d%Urgence%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-10', (SELECT id FROM users WHERE fullname LIKE '%Ahlem Lellahom%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Compresseur%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-11', (SELECT id FROM users WHERE fullname LIKE '%Hatem Ben Brahim%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%BBG Verts%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-12', (SELECT id FROM users WHERE fullname LIKE '%Dalel Ben Dhieb%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Bac %'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-16', (SELECT id FROM users WHERE fullname LIKE '%Hatem Ben Brahim%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%D%tecteurs%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-17', (SELECT id FROM users WHERE fullname LIKE '%Rim Ben Boujemaa%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Armoires %lectriques%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-19', (SELECT id FROM users WHERE fullname LIKE '%Ahlem Lellahom%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Portes Coupe-Feu%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-20', (SELECT id FROM users WHERE fullname LIKE '%Dalel Ben Dhieb%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Portes Secours%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-21', (SELECT id FROM users WHERE fullname LIKE '%Ahlem Lellahom%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Kit de D%versement%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-23', (SELECT id FROM users WHERE fullname LIKE '%Toute%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Extincteurs%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-24', (SELECT id FROM users WHERE fullname LIKE '%Rim Ben Boujemaa%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%BBG Verts%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-25', (SELECT id FROM users WHERE fullname LIKE '%Ahlem Lellahom%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%TGBT%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-26', (SELECT id FROM users WHERE fullname LIKE '%Dalel Ben Dhieb%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Compresseur%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-29', (SELECT id FROM users WHERE fullname LIKE '%Rim Ben Boujemaa%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Zones de Stockage%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-30', (SELECT id FROM users WHERE fullname LIKE '%Hatem Ben Brahim%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%Pompe %'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW()),
('2026-07-31', (SELECT id FROM users WHERE fullname LIKE '%Hatem Ben Brahim%'), (SELECT id FROM checklist_templates WHERE template_name LIKE '%D%tecteurs%'), (SELECT id FROM sites WHERE site_name LIKE '%CCTV%'), 'CCTV Facility', 'Planned', NOW());
